version: '3.3'
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/usr/src/app"
    ports:
      - "4000:4000"
    command: "bundle exec jekyll serve --host 0.0.0.0"
    